# This is a basic workflow to help you get started with Actions

name: Auto-merge-master-develop

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  pull_request:
    branches: [master]
    types: [closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  merge-master-to-dev:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # If master pull request is merged 
    if: github.event.pull_request.merged == true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set Git config
        run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "Github Actions"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.11.0
        with:
          branch: master
          base: develop
          title: update develop from master
          commit-message: auto PR master to develop
          delete-branch: true
